### ISSUE TITLE
multiple POS for a single ontolex:LexicalEntry 

### ISSUE THREAD

**Issue by vocabulista** [elexis-eu/tei2ontolex#15]
In PLI_1906_20190109 sample.xml `ontolex:LexicalEntry rdf:ID="abaisseur"` has 2 associated `lexinfo:partOfSpeech`. This is not conform with OntoLex-Lemon's core module: one POS per LexicalEntry.

https://github.com/elexis-eu/tei2ontolex/blob/691da1e724c1fcfde4bd4491c95f11af58601935/GeneratedOntolex/PLI_1906_20190109%20sample.xml#L439-L454

**Comment by jmccrae** [comment]
We should generate two entries for each part of speech. They can be grouped together with `<lexicog:Entry>` tags like in #14

**Comment by laurentromary** [comment]
I have implemented the splitting. Please check that the output for "abaisseur" is correct.

**Comment by jmccrae** [comment]
The output in XML should look something like this

```xml
  <lexicog:Entry rdf:ID="abaisseur">
    <lexicog:describes>
      <ontolex:LexicalEntry rdf:ID="abaisseur-1">
      ...
    </lexicog:describes>    
    <lexicog:describes>
      <ontolex:LexicalEntry rdf:ID="abaisseur-2">
      ...
    </lexicog:describes>
  </lexicog:Entry>
```

**Comment by laurentromary** [comment]
I should be working now.

**Comment by laurentromary** [comment]
I should be working now.
